-- ═══════════════════════════════════════════════════════════════════════
-- RECONSTRUCTED DATABASE SCHEMA — cre8connect
-- ═══════════════════════════════════════════════════════════════════════
--
-- Generated by: Deep codebase reverse-engineering scan
-- Date:         2026-04-28
-- Scope:        campagne, produit, campagne_produit
--
-- This file reconciles the original "Base de Donnee.sql" with the ACTUAL
-- column usage found across ALL controllers, models, and views.
--
-- Legend:
--   [BASELINE]  = column present in original SQL and still used
--   [RENAMED]   = column exists in original SQL under a different name
--   [NEW]       = column NOT in original SQL, added later
--   [DROPPED]   = column in original SQL but NOT used anywhere in code
--   [ENUM-CHG]  = ENUM values differ from original SQL
-- ═══════════════════════════════════════════════════════════════════════

-- NOTE: The tables `utilisateur`, `reclamation`, `post`, `comment`,
--       `offre`, `candidature`, `contrat`, `evenement`, `forum`, and
--       `evenement_produit` are UNCHANGED from the original schema.
--       Only the 3 tables below have discrepancies.


-- ─────────────────────────────────────────────────────────────────────
-- 1) campagne
-- ─────────────────────────────────────────────────────────────────────
-- CHANGES vs. original:
--   • titre        → RENAMED to titreCampagne
--   • idCandidature → DROPPED (not used in any INSERT/UPDATE/SELECT)
--   • FK fk_campagne_candidature → DROPPED
--   • UNIQUE KEY uq_campagne_candidature → DROPPED
--   • statut ENUM  → VALUES CHANGED (see below)
--   • budget       → NEW
--   • objectif     → NEW
--   • estArchive   → NEW
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS campagne (
    -- [BASELINE] Primary key
    idCampagne    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    -- [BASELINE] FK → utilisateur(id)
    idMarque      INT UNSIGNED NOT NULL,

    -- [DROPPED]  idCandidature was in original schema but is NOT used
    --            in any controller INSERT/UPDATE. Removed.
    -- idCandidature INT UNSIGNED NOT NULL,   -- ❌ DROPPED

    -- [RENAMED]  Original: titre VARCHAR(150)
    --            All SQL queries use 'titreCampagne' (INSERT, UPDATE, SELECT)
    titreCampagne VARCHAR(150) NOT NULL,

    -- [BASELINE] Unchanged
    description   TEXT NOT NULL,

    -- [BASELINE] Unchanged
    dateDebut     DATE NOT NULL,

    -- [BASELINE] Unchanged
    dateFin       DATE NOT NULL,

    -- [NEW] Budget — used in INSERT/UPDATE; displayed as currency in all views
    --       Source: campagneC.php INSERT + all FO/BO views
    budget        DECIMAL(10,2) NOT NULL DEFAULT 0.00,

    -- [ENUM-CHG] Original: ENUM('planifiee','en_cours','terminee','suspendue','annulee')
    --            Code uses:  'active', 'brouillon', 'terminee', 'annulee', 'archivee'
    --            Evidence:   FO/BO views, archiverCampagne(), desarchiverCampagne()
    statut        ENUM('active', 'brouillon', 'terminee', 'annulee', 'archivee')
                  NOT NULL DEFAULT 'brouillon',

    -- [NEW] Objective — displayed with 🎯 in views; conditionally shown
    --       Source: campagneC.php INSERT/UPDATE; all views
    objectif      TEXT DEFAULT NULL,

    -- [NEW] Soft-archive flag — used for archive/restore toggle
    --       Source: campagneC.php archiverCampagne()/desarchiverCampagne()
    --       Filter: WHERE estArchive = 0 in afficherCampagnes()
    estArchive    TINYINT(1) NOT NULL DEFAULT 0,

    -- FK to utilisateur (brand account) — KEPT from original
    CONSTRAINT fk_campagne_marque
        FOREIGN KEY (idMarque) REFERENCES utilisateur(id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    -- DROPPED: fk_campagne_candidature (column removed)
    -- DROPPED: uq_campagne_candidature  (column removed)

    KEY idx_campagne_marque  (idMarque),
    KEY idx_campagne_statut  (statut),
    KEY idx_campagne_archive (estArchive)
) ENGINE=InnoDB;


-- ─────────────────────────────────────────────────────────────────────
-- 2) produit
-- ─────────────────────────────────────────────────────────────────────
-- CHANGES vs. original:
--   All 6 original columns KEPT as-is.
--   7 NEW columns added (exact types from migrerColonnes() method)
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS produit (
    -- [BASELINE] Primary key
    idProduit         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    -- [BASELINE] FK → utilisateur(id)
    idMarque          INT UNSIGNED NOT NULL,

    -- [BASELINE] Unchanged
    nomProduit        VARCHAR(150) NOT NULL,

    -- [BASELINE] Unchanged
    description       TEXT NOT NULL,

    -- [BASELINE] Unchanged — used as comma-separated tags in views
    caracteristiques  TEXT NOT NULL,

    -- [BASELINE] Unchanged
    prix              DECIMAL(10,2) NOT NULL,

    -- ┌──────────────────────────────────────────────────────────────┐
    -- │  NEW COLUMNS — added via migrerColonnes() in produitC.php   │
    -- │  Exact types taken from the ALTER TABLE statements there.   │
    -- └──────────────────────────────────────────────────────────────┘

    -- [NEW] Product image filename (stored in Vue/public/produits/)
    image             VARCHAR(255) DEFAULT NULL,

    -- [NEW] Product category (filterable, DISTINCT-queried)
    categorie         VARCHAR(100) DEFAULT NULL,

    -- [NEW] Soft-archive flag — WHERE estArchive = 0
    estArchive        TINYINT(1) DEFAULT 0,

    -- [NEW] Featured/pinned flag — special UI treatment in all views
    estEpingle        TINYINT(1) DEFAULT 0,

    -- [NEW] Manual sort order — ORDER BY sortOrder ASC
    sortOrder         INT DEFAULT 0,

    -- [NEW] Availability date — future vs. past logic in views
    dateDisponibilite DATE DEFAULT NULL,

    -- [NEW] Internal brand notes — only shown in BackOffice
    noteInterne       TEXT DEFAULT NULL,

    -- FK to utilisateur (brand account) — KEPT from original
    CONSTRAINT fk_produit_marque
        FOREIGN KEY (idMarque) REFERENCES utilisateur(id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    KEY idx_produit_marque    (idMarque),
    KEY idx_produit_categorie (categorie),
    KEY idx_produit_archive   (estArchive)
) ENGINE=InnoDB;


-- ─────────────────────────────────────────────────────────────────────
-- 3) campagne_produit  (junction table — UNCHANGED)
-- ─────────────────────────────────────────────────────────────────────
-- No discrepancies found. All code uses only idCampagne + idProduit.
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS campagne_produit (
    idCampagne  INT UNSIGNED NOT NULL,
    idProduit   INT UNSIGNED NOT NULL,

    PRIMARY KEY (idCampagne, idProduit),

    CONSTRAINT fk_campagne_produit_campagne
        FOREIGN KEY (idCampagne) REFERENCES campagne(idCampagne)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT fk_campagne_produit_produit
        FOREIGN KEY (idProduit) REFERENCES produit(idProduit)
        ON DELETE CASCADE ON UPDATE CASCADE,

    KEY idx_campagne_produit_produit (idProduit)
) ENGINE=InnoDB;


-- ═══════════════════════════════════════════════════════════════════════
-- MIGRATION HELPER — If you need to ALTER the existing tables
-- instead of recreating them, use these statements:
-- ═══════════════════════════════════════════════════════════════════════

/*
-- ── campagne: apply changes to existing table ─────────────────────

-- 1. Rename titre → titreCampagne
ALTER TABLE campagne CHANGE titre titreCampagne VARCHAR(150) NOT NULL;

-- 2. Drop idCandidature FK + UNIQUE + column
ALTER TABLE campagne DROP FOREIGN KEY fk_campagne_candidature;
ALTER TABLE campagne DROP INDEX uq_campagne_candidature;
ALTER TABLE campagne DROP COLUMN idCandidature;

-- 3. Change statut ENUM
ALTER TABLE campagne MODIFY statut
    ENUM('active','brouillon','terminee','annulee','archivee')
    NOT NULL DEFAULT 'brouillon';

-- 4. Add new columns
ALTER TABLE campagne ADD COLUMN budget     DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER dateFin;
ALTER TABLE campagne ADD COLUMN objectif   TEXT DEFAULT NULL AFTER statut;
ALTER TABLE campagne ADD COLUMN estArchive TINYINT(1) NOT NULL DEFAULT 0;

-- 5. Add index
ALTER TABLE campagne ADD KEY idx_campagne_archive (estArchive);


-- ── produit: apply changes to existing table ──────────────────────

ALTER TABLE produit ADD COLUMN image             VARCHAR(255) DEFAULT NULL;
ALTER TABLE produit ADD COLUMN categorie         VARCHAR(100) DEFAULT NULL;
ALTER TABLE produit ADD COLUMN estArchive        TINYINT(1) DEFAULT 0;
ALTER TABLE produit ADD COLUMN estEpingle        TINYINT(1) DEFAULT 0;
ALTER TABLE produit ADD COLUMN sortOrder         INT DEFAULT 0;
ALTER TABLE produit ADD COLUMN dateDisponibilite DATE DEFAULT NULL;
ALTER TABLE produit ADD COLUMN noteInterne       TEXT DEFAULT NULL;

ALTER TABLE produit ADD KEY idx_produit_categorie (categorie);
ALTER TABLE produit ADD KEY idx_produit_archive   (estArchive);
*/
